version: "3.9"

# Volulme for storing mongo data and making it persistent
volumes:
    mongo_data:
        driver: local

services:
    mongo:
        # container_name: mongo
        image: mvertes/alpine-mongo
        ports:
            - "27017:27017"
        volumes:
            - "mongo_data:/data/db"
    frontend:
        # container_name: frontend
        build: /frontend
        image: frontend:v1
        ports:
            - "3000:3000"
        depends_on:
            - backend
    backend:
        # container_name: backend
        build: /backend
        image: backend:v1
        deploy:
            replicas: 4
            update_config:
                parallelism: 5
                delay: 10s
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        ports:
            - "5000:5000"
    server:
        # container_name: server
        image: nginx:1.21.0-alpine
        ports:
            - "80:80"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
