version: "3.9"

volumes:
  mongo_data:
    driver: local

networks:
  boilerplate:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    networks:
      - boilerplate
    restart: always

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - boilerplate
    volumes:
      - "./backend:/backend"
      - "/backend/node_modules"
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - boilerplate
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
      - "/frontend/.next"
    restart: always
    depends_on:
      - backend
